### PR TITLE
Add neovim v2 API

### PR DESCRIPTION
**Pull request by jamesnvc**

### CODE REVIEW

**Comment by hkupty** [comment]
I'm against having all this functions manually defined here... Not only this is an enormous repetition of code but also we're prone to changes in the API causing a cascade of bumps.

It'd be great if those functions could be generated automatically (i.e. from a macro) given a clients preference of using any desired version of neovim's API.

**Comment by jamesnvc** [comment]
For sure! I actually started a branch to do just that; I just did it this way as that's what the existing code was doing.  I'll resurrect my macro version & submit a PR for that.

**Comment by jebberjeb** [comment]
I'd love to see a way out of storing the generated code, while still keeping namespaces api versioned, and accessible to plugin developers at eval time. In other words, I think forcing a plugin developer to perform some ceremony before their code will even evaluate might be an issue. 

Totally open to discussion on this -- this was just my first real stab at it.

**Comment by jamesnvc** [comment]
I was considering having some sort of macro to generate the definitions, so you could have `2/api.clj` which would just contain `(generate-api-functions 2)` or something like that. My concern was it would be fairly opaque and kind of a pain if you wanted to see what functions were available without having to do a `macroexpand-1` or `ns-publics` or what have you.

**Comment by hkupty** [comment]
I and @jebberjeb were having a fruitful debate over some ideas and it seemed much better for both sides - our side, as maintainers of this library and plugin authors side as well - if, instead of generating the code upon compilation, we still generate static code, but leave it on the client (i.e. the plugin using neovim-client). 

In other words, a plugin author would, once, prompt neovim-client to generate the API functions. This, no matter how we implement it, would produce the client code beside the plugins source. 

This lifts off the burden of keeping several implementations on our side while still follows the API schema in a way that the client has access to the actual functions. 

This also has several minor benefits, as we can focus on the code that generates the API client code rather than the actual implementation, so we can add support for spec or core.async, for example. 

This is not written on stone and we're open to discussing it. 

Cheers, 
Henry Kupty

**Comment by jebberjeb** [comment]
Agreed. I like the fact that it is simple -- docs instruct the plugin author to run some function at the repl or even a bash script. A little ceremony, but probably something that a plugin author wouldn't balk at. But I have some questions.

Assuming a few things (regardless of which strategy we use)

* We as library authors would never directly change the generated code -- we would only ever modify the generator then regenerate the code.

* Metadata for an API level is consistent. It doesn't matter whether we generate the code, or the plugin dev does it, the result is the same.

*  API levels change very rarely (there have only been 3 (0-2) in roughly 3 years now.

Is storing a handful of source files really that much of a burden? We'd never modify them directly. Their sole purpose is to provide a "normal" experience to a plugin dev consuming a Clojure library. `ns-publics`, `doc`, etc all work as expected.

Either way, we have to make sure that the generating code works with all API levels, and is unit tested against those levels, etc. As far as the burden of having to generate code and version the library when a new API level is released, that's not uncommon for a client library for an API.

A nice side effect of storing the generated code is that we can make sure that only non-debug, release Neovim builds are used to procure the metadata. We'd be ensuring that if you use our client library to build a plugin, your code will be portable. Not necessarily true of a plugin created using client code generated from a debug Neovim build, for example.

We could still expose the generator to plugin devs that don't want to wait for us to add an API version, or want to use a debug version's API metdata.

What I'd really like to see is a concrete example of how this would benefit us. What specific problem would we not have if we push generation to the plugin dev? I'd never really considered maintaining the generated code a problem -- it's generated.

**Comment by SevereOverfl0w** [comment]
> We'd be ensuring that if you use our client library to build a plugin, your code will be portable. Not necessarily true of a plugin created using client code generated from a debug Neovim build, for example.

Is there a use case where you wish to build something using a newer neovim api feature, and have the plugin ready for others to test & before a stable release is out?

If it's dynamic, it's easier to distrubte. The plugin instructs the user: This only works with cfbee14 and up, use a dev build! If it's static, the instructions involve installing a fork/branch of this repo in order to use the beta plugin.

**Comment by jebberjeb** [comment]
> Is there a use case where you wish to build something using a newer neovim api feature, and have the plugin ready for others to test & before a stable release is out?

> If it's dynamic, it's easier to distrubte. The plugin instructs the user: This only works with cfbee14 and up, use a dev build! If it's static, the instructions involve installing a fork/branch of this repo in order to use the beta plugin.

I'm tempted to say that we could probably expose this ability while also shipping release versioned code with the client but that would complicate the docs, and the code a little at least.

Yes, I think I'd definitely want to easily create and distribute a plugin using a dev build's API features. Even though that could potentially result in code that isn't forward compatible, I'd want to do it, and having users install a fork of the client repo would be a deal breaker. So I think I'm on board with a one-time generation of client code by the plugin dev solution.

**Comment by jebberjeb** [comment]
I suppose there's no reason that someone couldn't simply generate the release versioned code and put it on Clojars to provide a ceremony-less experience for plugin devs -- if they felt that was important.

**Pull request closed without merging**
